sudo python -m pip --version
sudo python -m install flash
sudo python -m install uuid
sudo python -m install platform
sudo python -m install numpy
sudo python -m install socket
sudo python -m install itertools
sudo python -m install re
sudo python -m install requests
